### PR TITLE
Add details/summary collapsing

### PR DESCRIPTION
**Pull request by kevinmarks**
Also escape name so my post with &lt;style&gt; in the name doesn't break the feed

### CODE REVIEW

**Comment by karadaisy** [comment]
I don't understand the thing about putting &lt;style> in the title?

**Comment by kevinmarks** [comment]
If you subscribe to kevinmarks.com, the post "u- means &lt;style&gt;" was being converted to a style tag and hiding the rest of the items

**Comment by karadaisy** [comment]
Got it, yep that makes sense, thanks!

**Comment by jeena** [comment]
The escape in the title should have fixed https://github.com/kylewm/woodwind/issues/37 so we could close it, did it?

**Comment by karadaisy** [comment]
Ha! Yep you're right, i forget all about that

**Pull request merged**
